# This is a config for E2B sandbox template.
# You can use template ID (ilklrwt25362axwtwc4w) or template name (vanguox-nextjs-8) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vanguox-nextjs-8") # Sync sandbox
# sandbox = await AsyncSandbox.create("vanguox-nextjs-8") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vanguox-nextjs-8')

team_id = "38c57808-285e-4118-b5fd-54d636f5bed3"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vanguox-nextjs-8"
template_id = "ilklrwt25362axwtwc4w"
